<?php
$produtos = [
    [ 'nome' => 'Bolo de Cenoura', 'foto' => 'bolo-cenoura.jpg', 'valor' => 60.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de Amendoim', 'foto' => 'bolo-amendoim.jpg', 'valor' => 60.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de KitKat', 'foto' => 'bolo-kitkat.jpg', 'valor' => 65.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de Marshmallow', 'foto' => 'bolo-marshmallow.jpg', 'valor' => 40.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de Abacaxi com Coco', 'foto' => 'bolo-abacaxi-com-coco.jpg', 'valor' => 45.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de Prestígio', 'foto' => 'bolo-prestígio.jpg', 'valor' => 50.00, 'destaque' => true ],
    [ 'nome' => 'Bolo de Frutas Vermelhas', 'foto' => 'bolo-frutas-vermelhas.jpg', 'valor' => 60.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de Maracujá', 'foto' => 'bolo-maracuja.jpg', 'valor' => 60.00, 'destaque' => true ],
    [ 'nome' => 'Bolo de Paçoca', 'foto' => 'bolo-pacoca.jpg', 'valor' => 70.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de Chocolate', 'foto' => 'bolo-chocolate.jpg', 'valor' => 65.00, 'destaque' => true ],
    [ 'nome' => 'Bolo de Trufado', 'foto' => 'bolo-trufado.jpg', 'valor' => 60.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de Oreo', 'foto' => 'bolo-oreo.jpg', 'valor' => 55.00, 'destaque' => true ],
    [ 'nome' => 'Bolo de Doce de Leite', 'foto' => 'bolo-doce-de-leite.jpg', 'valor' => 60.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de Brigadeiro', 'foto' => 'bolo-brigadeiro.jpg', 'valor' => 46.00, 'destaque' => true ],
    [ 'nome' => 'Bolo de Leite Ninho', 'foto' => 'bolo-leite-ninho.jpg', 'valor' => 58.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de Limão', 'foto' => 'bolo-limao.jpg', 'valor' => 60.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de Morango', 'foto' => 'bolo-morango.jpg', 'valor' => 42.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de Banana', 'foto' => 'bolo-banana.jpg', 'valor' => 48.00, 'destaque' => true ],
    [ 'nome' => 'Bolo de Romeu e Julieta', 'foto' => 'bolo-romeu-julieta.jpg', 'valor' => 60.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de Red Velvet', 'foto' => 'bolo-red-velvet.jpg', 'valor' => 50.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de Churros', 'foto' => 'bolo-churros.jpg', 'valor' => 45.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de Nozes', 'foto' => 'bolo-nozes.jpg', 'valor' => 60.00, 'destaque' => true ],
    [ 'nome' => 'Bolo de Coco', 'foto' => 'bolo-coco.jpg', 'valor' => 45.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de Chocolate com Morango', 'foto' => 'bolo-chocolate-morango.jpg', 'valor' => 60.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de Maracujá Trufado', 'foto' => 'bolo-maracuja-trufado.jpg', 'valor' => 65.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de Ninho com Nutella', 'foto' => 'bolo-ninho-nutella.jpg', 'valor' => 65.00, 'destaque' => true ],
    [ 'nome' => 'Bolo de Paçoca com Chocolate', 'foto' => 'bolo-pacoca-chocolate.jpg', 'valor' => 50.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de Limão com Merengue', 'foto' => 'bolo-limao-merengue.jpg', 'valor' => 65.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de Chocolate Branco', 'foto' => 'bolo-chocolate-branco.jpg', 'valor' => 45.00, 'destaque' => false ],
    [ 'nome' => 'Bolo de Caramelo', 'foto' => 'bolo-caramelo.jpg', 'valor' => 40.00, 'destaque' => false ],

];
?>
