<?php
$produtos = [
    [ 'nome' => 'Bolo de Cenoura', 'foto' => 'bolo-cenoura.jpg', 'valor' => 62.26, 'destaque' => false ],
    [ 'nome' => 'Bolo de Amendoim', 'foto' => 'bolo-amendoim.jpg', 'valor' => 60.05, 'destaque' => false ],
    [ 'nome' => 'Bolo de KitKat', 'foto' => 'bolo-kitkat.jpg', 'valor' => 66.51, 'destaque' => false ],
    [ 'nome' => 'Bolo de Marshmallow', 'foto' => 'bolo-marshmallow.jpg', 'valor' => 41.39, 'destaque' => false ],
    [ 'nome' => 'Bolo de Abacaxi com Coco', 'foto' => 'bolo-abacaxi-com-coco.jpg', 'valor' => 46.20, 'destaque' => false ],
    [ 'nome' => 'Bolo de Prestígio', 'foto' => 'bolo-prestígio.jpg', 'valor' => 51.04, 'destaque' => true ],
    [ 'nome' => 'Bolo de Frutas Vermelhas', 'foto' => 'bolo-frutas-vermelhas.jpg', 'valor' => 60.89, 'destaque' => false ],
    [ 'nome' => 'Bolo de Maracujá', 'foto' => 'bolo-maracuja.jpg', 'valor' => 57.21, 'destaque' => true ],
    [ 'nome' => 'Bolo de Paçoca', 'foto' => 'bolo-pacoca.jpg', 'valor' => 67.18, 'destaque' => false ],
    [ 'nome' => 'Bolo de Chocolate', 'foto' => 'bolo-chocolate.jpg', 'valor' => 66.01, 'destaque' => false ],
    [ 'nome' => 'Bolo de Trufado', 'foto' => 'bolo-trufado.jpg', 'valor' => 62.48, 'destaque' => false ],
    [ 'nome' => 'Bolo de Oreo', 'foto' => 'bolo-oreo.jpg', 'valor' => 52.30, 'destaque' => true ],
    [ 'nome' => 'Bolo de Doce de Leite', 'foto' => 'bolo-doce-de-leite.jpg', 'valor' => 60.45, 'destaque' => false ],
    [ 'nome' => 'Bolo de Brigadeiro', 'foto' => 'bolo-brigadeiro.jpg', 'valor' => 46.93, 'destaque' => false ],
    [ 'nome' => 'Bolo de Leite Ninho', 'foto' => 'bolo-leite-ninho.jpg', 'valor' => 58.77, 'destaque' => false ],
    [ 'nome' => 'Bolo de Limão', 'foto' => 'bolo-limao.jpg', 'valor' => 60.01, 'destaque' => false ],
    [ 'nome' => 'Bolo de Morango', 'foto' => 'bolo-morango.jpg', 'valor' => 42.68, 'destaque' => false ],
    [ 'nome' => 'Bolo de Banana', 'foto' => 'bolo-banana.jpg', 'valor' => 48.00, 'destaque' => true ],
    [ 'nome' => 'Bolo de Romeu e Julieta', 'foto' => 'bolo-romeu-julieta.jpg', 'valor' => 60.56, 'destaque' => false ],
    [ 'nome' => 'Bolo de Red Velvet', 'foto' => 'bolo-red-velvet.jpg', 'valor' => 49.82, 'destaque' => false ],
    [ 'nome' => 'Bolo de Churros', 'foto' => 'bolo-churros.jpg', 'valor' => 43.98, 'destaque' => false ],
    [ 'nome' => 'Bolo de Nozes', 'foto' => 'bolo-nozes.jpg', 'valor' => 62.78, 'destaque' => true ],
    [ 'nome' => 'Bolo de Coco', 'foto' => 'bolo-coco.jpg', 'valor' => 44.32, 'destaque' => false ],
    [ 'nome' => 'Bolo de Chocolate com Morango', 'foto' => 'bolo-chocolate-morango.jpg', 'valor' => 59.75, 'destaque' => true ],
    [ 'nome' => 'Bolo de Maracujá Trufado', 'foto' => 'bolo-maracuja-trufado.jpg', 'valor' => 66.63, 'destaque' => false ],
    [ 'nome' => 'Bolo de Ninho com Nutella', 'foto' => 'bolo-ninho-nutella.jpg', 'valor' => 65.44, 'destaque' => true ],
    [ 'nome' => 'Bolo de Paçoca com Chocolate', 'foto' => 'bolo-pacoca-chocolate.jpg', 'valor' => 49.55, 'destaque' => false ],
    [ 'nome' => 'Bolo de Limão com Merengue', 'foto' => 'bolo-limao-merengue.jpg', 'valor' => 64.88, 'destaque' => false ],
    [ 'nome' => 'Bolo de Chocolate Branco', 'foto' => 'bolo-chocolate-branco.jpg', 'valor' => 43.42, 'destaque' => false ],
    [ 'nome' => 'Bolo de Caramelo', 'foto' => 'bolo-caramelo.jpg', 'valor' => 42.71, 'destaque' => false ],
    [ 'nome' => 'Bolo de Morango com Chantilly', 'foto' => 'bolo-morango-chantilly.jpg', 'valor' => 68.99, 'destaque' => false ],
    [ 'nome' => 'Bolo de Abacaxi com Creme', 'foto' => 'bolo-abacaxi-creme.jpg', 'valor' => 54.77, 'destaque' => false ],
    [ 'nome' => 'Bolo de Frutas Tropicais', 'foto' => 'bolo-frutas-tropicais.jpg', 'valor' => 69.17, 'destaque' => false ],
    [ 'nome' => 'Bolo de Leite Condensado', 'foto' => 'bolo-leite-condensado.jpg', 'valor' => 60.38, 'destaque' => true ],
    [ 'nome' => 'Bolo de Chocolate Trufado', 'foto' => 'bolo-chocolate-trufado.jpg', 'valor' => 63.82, 'destaque' => false ],
    [ 'nome' => 'Bolo de Uva com Leite Ninho', 'foto' => 'bolo-uva-ninho.jpg', 'valor' => 50.66, 'destaque' => false ],
    [ 'nome' => 'Bolo de Amêndoas', 'foto' => 'bolo-amendoas.jpg', 'valor' => 51.33, 'destaque' => false ],
    [ 'nome' => 'Bolo de Nutella', 'foto' => 'bolo-nutella.jpg', 'valor' => 45.21, 'destaque' => true ],
    [ 'nome' => 'Bolo de Maracujá com Chocolate', 'foto' => 'bolo-maracuja-chocolate.jpg', 'valor' => 48.85, 'destaque' => false ],
    [ 'nome' => 'Bolo de Morango com Ninho', 'foto' => 'bolo-morango-ninho.jpg', 'valor' => 47.59, 'destaque' => false ],
    [ 'nome' => 'Bolo de Café', 'foto' => 'bolo-cafe.jpg', 'valor' => 56.32, 'destaque' => false ],
    [ 'nome' => 'Bolo de Chocolate Meio Amargo', 'foto' => 'bolo-chocolate-meio-amargo.jpg', 'valor' => 55.40, 'destaque' => false ],
    [ 'nome' => 'Bolo de Sorvete', 'foto' => 'bolo-sorvete.jpg', 'valor' => 67.75, 'destaque' => true ],
    [ 'nome' => 'Bolo de Cheesecake', 'foto' => 'bolo-cheesecake.jpg', 'valor' => 53.09, 'destaque' => false ],
    [ 'nome' => 'Bolo de Milho', 'foto' => 'bolo-milho.jpg', 'valor' => 43.27, 'destaque' => false ],
    [ 'nome' => 'Bolo de Chocolate com Paçoca', 'foto' => 'bolo-chocolate-pacoca.jpg', 'valor' => 65.87, 'destaque' => true ],
    [ 'nome' => 'Bolo de Goiabada', 'foto' => 'bolo-goiabada.jpg', 'valor' => 58.61, 'destaque' => false ],
    [ 'nome' => 'Bolo de Beijinho', 'foto' => 'bolo-beijinho.jpg', 'valor' => 67.31, 'destaque' => false ],
    [ 'nome' => 'Bolo de Chocolate com Laranja', 'foto' => 'bolo-chocolate-laranja.jpg', 'valor' => 64.90, 'destaque' => false ]
];
?>
