<?php
$produtos = [
    [ 'nome' => 'Bolo de Cenoura', 'foto' => 'bolo-cenoura.jpg', 'valor' => 62.26, 'destaque' => false ],
    [ 'nome' => 'Bolo de Amendoim', 'foto' => 'bolo-amendoim.jpg', 'valor' => 60.05, 'destaque' => false ],
    [ 'nome' => 'Bolo de KitKat', 'foto' => 'bolo-kitkat.jpg', 'valor' => 66.51, 'destaque' => false ],
    [ 'nome' => 'Bolo de Marshmallow', 'foto' => 'bolo-marshmallow.jpg', 'valor' => 41.39, 'destaque' => false ],
    [ 'nome' => 'Bolo de Abacaxi com Coco', 'foto' => 'bolo-abacaxi-com-coco.jpg', 'valor' => 46.20, 'destaque' => false ],
    [ 'nome' => 'Bolo de Prestígio', 'foto' => 'bolo-prestígio.jpg', 'valor' => 51.04, 'destaque' => true ],
    [ 'nome' => 'Bolo de Frutas Vermelhas', 'foto' => 'bolo-frutas-vermelhas.jpg', 'valor' => 60.89, 'destaque' => false ],
    [ 'nome' => 'Bolo de Maracujá', 'foto' => 'bolo-maracuja.jpg', 'valor' => 57.21, 'destaque' => true ],
    [ 'nome' => 'Bolo de Paçoca', 'foto' => 'bolo-pacoca.jpg', 'valor' => 67.18, 'destaque' => false ],
    [ 'nome' => 'Bolo de Chocolate', 'foto' => 'bolo-chocolate.jpg', 'valor' => 66.01, 'destaque' => true ],
    [ 'nome' => 'Bolo de Trufado', 'foto' => 'bolo-trufado.jpg', 'valor' => 62.48, 'destaque' => false ],
    [ 'nome' => 'Bolo de Oreo', 'foto' => 'bolo-oreo.jpg', 'valor' => 52.30, 'destaque' => true ],
    [ 'nome' => 'Bolo de Doce de Leite', 'foto' => 'bolo-doce-de-leite.jpg', 'valor' => 60.45, 'destaque' => false ],
    [ 'nome' => 'Bolo de Brigadeiro', 'foto' => 'bolo-brigadeiro.jpg', 'valor' => 46.93, 'destaque' => false ],
    [ 'nome' => 'Bolo de Leite Ninho', 'foto' => 'bolo-leite-ninho.jpg', 'valor' => 58.77, 'destaque' => false ],
    [ 'nome' => 'Bolo de Limão', 'foto' => 'bolo-limao.jpg', 'valor' => 60.01, 'destaque' => false ],
    [ 'nome' => 'Bolo de Morango', 'foto' => 'bolo-morango.jpg', 'valor' => 42.68, 'destaque' => false ],
    [ 'nome' => 'Bolo de Banana', 'foto' => 'bolo-banana.jpg', 'valor' => 48.00, 'destaque' => true ],
    [ 'nome' => 'Bolo de Romeu e Julieta', 'foto' => 'bolo-romeu-julieta.jpg', 'valor' => 60.56, 'destaque' => false ],
    [ 'nome' => 'Bolo de Red Velvet', 'foto' => 'bolo-red-velvet.jpg', 'valor' => 49.82, 'destaque' => false ],
    [ 'nome' => 'Bolo de Churros', 'foto' => 'bolo-churros.jpg', 'valor' => 43.98, 'destaque' => false ],
    [ 'nome' => 'Bolo de Nozes', 'foto' => 'bolo-nozes.jpg', 'valor' => 62.78, 'destaque' => true ],
    [ 'nome' => 'Bolo de Coco', 'foto' => 'bolo-coco.jpg', 'valor' => 44.32, 'destaque' => false ],
    [ 'nome' => 'Bolo de Chocolate com Morango', 'foto' => 'bolo-chocolate-morango.jpg', 'valor' => 59.75, 'destaque' => true ],
    [ 'nome' => 'Bolo de Maracujá Trufado', 'foto' => 'bolo-maracuja-trufado.jpg', 'valor' => 66.63, 'destaque' => false ],
    [ 'nome' => 'Bolo de Ninho com Nutella', 'foto' => 'bolo-ninho-nutella.jpg', 'valor' => 65.44, 'destaque' => true ],
    [ 'nome' => 'Bolo de Paçoca com Chocolate', 'foto' => 'bolo-pacoca-chocolate.jpg', 'valor' => 49.55, 'destaque' => false ],
    [ 'nome' => 'Bolo de Limão com Merengue', 'foto' => 'bolo-limao-merengue.jpg', 'valor' => 64.88, 'destaque' => false ],
    [ 'nome' => 'Bolo de Chocolate Branco', 'foto' => 'bolo-chocolate-branco.jpg', 'valor' => 43.42, 'destaque' => false ],
    [ 'nome' => 'Bolo de Caramelo', 'foto' => 'bolo-caramelo.jpg', 'valor' => 42.71, 'destaque' => false ],

];
?>
